# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- welcome
- build
- analyze

welcome:
  stage: welcome
  only:
    - dev
  script:
    - echo -e "##################################\nTesting\n##################################"


build_preview:
  stage: build
  image: docker
  environment: preview
  services:
    - docker:dind
  only:
    - dev
  before_script:
    - docker --version
  script:
    - docker build -t $REGISTRY_SERVER/$REGISTRY_NAME:$MAJOR_VERSION.$MINOR_VERSION .
    - docker login --username $REGISTRY_USERNAME --password $REGISTRY_PASSWORD $REGISTRY_SERVER
    - docker push $REGISTRY_SERVER/$REGISTRY_NAME:$MAJOR_VERSION.$MINOR_VERSION


stages:
  - analyze
analyze:sonar:
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:4.5
    entrypoint: [""]
  variables:
    # Defines the location of the analysis task cache
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    # Shallow cloning needs to be disabled.
    # See https://docs.sonarqube.org/latest/analysis/gitlab-cicd/.
    GIT_DEPTH: 0
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  only: 
    - dev    
  script:
    - sonar-scanner
  rules:
    # SonarQube CommunityEdition only supports analyzing a single branch.
    # So only run on master.
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
    - when: never