version: '3.8'
networks:
  cpe_ctfd_dev_net:
    driver: bridge

services:
  database:
    image: postgres:14
    container_name: database.$DOMAIN
    environment:
      # timezone must be synchronized
      TZ: Asia/Bangkok
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    networks:
      - cpe_ctfd_dev_net
    ports:
      - $DB_PORT:5432
    volumes:
      - ~/om-persitance/postgresql:/var/lib/postgresql:rw

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin.$DOMAIN
    environment:
      TZ: Asia/Bangkok
      PGADMIN_DEFAULT_EMAIL: $DB_TOOL_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $DB_TOOL_PASSWORD
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
    networks:
      - cpe_ctfd_dev_net
